import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Endpoints',
      link: { type: 'generated-index', slug: '/endpoints' },
      items: [{ type: 'autogenerated', dirName: 'endpoints' }],
    },
    'billing-fields',
    'response-json',
    {
      type: 'category',
      label: 'Ejemplos JSON',
      link: {
        type: 'generated-index',
        slug: '/jsons-billing',
        title: 'Ejemplos JSON',
        description: 'Ejemplos de payloads en formato JSON divididos por categorías de documentos electrónicos.',
      },
      collapsible: true,
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'jsons-billing' },
        { type: 'autogenerated', dirName: 'jsons-pos' },
        { type: 'autogenerated', dirName: 'jsons-support-document' },
        { type: 'autogenerated', dirName: 'payroll' },
      ],
    },
    {
      type: 'category',
      label: 'Casos de Uso',
      collapsible: true,
      collapsed: true,
      items: [
        'use-cases/simple-invoice',
        'use-cases/invoice-with-discounts',
        'use-cases/export-scenarios',
        'use-cases/common-errors',
      ],
    },
    'glossary',
    'interactive-tools',
    {
      type: 'category',
      label: 'Marco Regulatorio',
      collapsible: true,
      collapsed: true,
      items: [
        'regulatory-framework/overview',
        { type: 'autogenerated', dirName: 'regulatory-framework/factura-electronica' },
        { type: 'autogenerated', dirName: 'regulatory-framework/nomina-electronica' },
        { type: 'autogenerated', dirName: 'regulatory-framework/documentos-equivalentes' },
        { type: 'autogenerated', dirName: 'regulatory-framework/documento-soporte' },
        { type: 'autogenerated', dirName: 'regulatory-framework/radian' },
        'regulatory-framework/tablas-referencia',
      ],
    },
  ],
};

export default sidebars;
