import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: '🔌 Endpoints',
      link: { type: 'generated-index', slug: '/endpoints' },
      items: [{ type: 'autogenerated', dirName: 'endpoints' }],
    },
    'bulk-documents',
    'billing-fields',
    'response-json',
    {
      type: 'category',
      label: 'Ejemplos JSON',
      link: {
        type: 'generated-index',
        slug: '/jsons-billing',
        title: 'Ejemplos JSON',
        description: 'Ejemplos de payloads en formato JSON divididos por categorías de documentos electrónicos.',
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Facturación',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            slug: '/jsons-billing/invoices',
          },
          items: [{ type: 'autogenerated', dirName: 'jsons-billing' }],
        },
        {
          type: 'category',
          label: 'POS',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            slug: '/jsons-pos/receipts',
          },
          items: [{ type: 'autogenerated', dirName: 'jsons-pos' }],
        },
        {
          type: 'category',
          label: 'Documento Soporte',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            slug: '/jsons-support-document/details',
          },
          items: [{ type: 'autogenerated', dirName: 'jsons-support-document' }],
        },
        {
          type: 'category',
          label: 'Nómina',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            slug: '/payroll/slips',
          },
          items: [{ type: 'autogenerated', dirName: 'payroll' }],
        },
      ],
    },
    {
      type: 'category',
      label: 'Casos de Uso',
      collapsible: true,
      collapsed: true,
      items: [
        'use-cases/simple-invoice',
        'use-cases/invoice-with-discounts',
        'use-cases/export-scenarios',
        'use-cases/common-errors',
      ],
    },
    {
      type: 'category',
      label: 'Sandbox',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        slug: '/sandbox',
        title: 'Sandbox de Pruebas',
        description: 'Ambiente de pruebas para integradores — mismos endpoints, respuestas simuladas de la DIAN.',
      },
      items: [
        'sandbox/quickstart',
        'sandbox/magic-values',
        'sandbox/test-cert',
        'sandbox/postman',
      ],
    },
    'glossary',
    'interactive-tools',
    {
      type: 'category',
      label: 'Marco Regulatorio',
      collapsible: true,
      collapsed: true,
      items: [
        'regulatory-framework/overview',
        { type: 'autogenerated', dirName: 'regulatory-framework/factura-electronica' },
        { type: 'autogenerated', dirName: 'regulatory-framework/nomina-electronica' },
        { type: 'autogenerated', dirName: 'regulatory-framework/documentos-equivalentes' },
        { type: 'autogenerated', dirName: 'regulatory-framework/documento-soporte' },
        { type: 'autogenerated', dirName: 'regulatory-framework/radian' },
        'regulatory-framework/tablas-referencia',
      ],
    },
  ],
};

export default sidebars;
