import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    // ============================================
    // SECCIÓN 1: INTRODUCCIÓN
    // ============================================
    {
      type: 'doc',
      id: 'intro',
      label: '🚀 Introducción',
    },

    // ============================================
    // SECCIÓN 2: INICIO RÁPIDO - GUÍAS DE CASO DE USO
    // ============================================
    {
      type: 'category',
      label: '🎓 Guías de Caso de Uso',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'use-cases/simple-invoice',
          label: '✨ Factura Simple (Principiante)',
        },
        {
          type: 'doc',
          id: 'use-cases/invoice-with-discounts',
          label: '💰 Factura con Descuentos',
        },
        {
          type: 'doc',
          id: 'use-cases/export-scenarios',
          label: '✈️ Escenarios de Exportación',
        },
        {
          type: 'doc',
          id: 'use-cases/common-errors',
          label: '🐛 Errores Comunes y Soluciones',
        },
      ],
    },

    // ============================================
    // SECCIÓN 3: REFERENCIA TÉCNICA
    // ============================================
    {
      type: 'category',
      label: '📚 Referencia Técnica',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'billing-fields',
          label: '🔧 Campos de Documentos',
        },
        {
          type: 'doc',
          id: 'glossary',
          label: '📚 Glosario Técnico',
        },
      ],
    },

    // ============================================
    // SECCIÓN 4: INTEGRACIÓN API
    // ============================================
    {
      type: 'category',
      label: '📡 Integración API',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'endpoints',
          label: 'Endpoints de la API',
        },
        {
          type: 'doc',
          id: 'response-json',
          label: 'Formato de Respuestas',
        },
      ],
    },

    // ============================================
    // SECCIÓN 5: HERRAMIENTAS INTERACTIVAS
    // ============================================
    {
      type: 'doc',
      id: 'interactive-tools',
      label: '⚙️ Herramientas Interactivas',
    },

    // ============================================
    // SECCIÓN 6: DOCUMENTOS ELECTRÓNICOS
    // ============================================
    {
      type: 'category',
      label: '📄 Ejemplos de Documentos',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: '📋 Factura Electrónica',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Ejemplos de Factura Electrónica',
            description: 'Colección completa de 26 ejemplos de facturas electrónicas, notas crédito/débito y casos especiales.',
            slug: '/ejemplos-facturacion',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'jsons-billing',
            },
          ],
        },
        {
          type: 'category',
          label: '🛒 POS (Punto de Venta)',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Ejemplos de POS Electrónico',
            description: 'Colección completa de 5 ejemplos de documentos POS (Punto de Venta), incluyendo ventas básicas, consumidor final y notas de ajuste.',
            slug: '/ejemplos-pos',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'jsons-pos',
            },
          ],
        },
        {
          type: 'category',
          label: '📦 Documento Soporte',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Ejemplos de Documento Soporte',
            description: 'Colección completa de 4 ejemplos de documentos soporte para adquisiciones a no obligados a facturar (residentes y no residentes).',
            slug: '/ejemplos-documento-soporte',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'jsons-support-document',
            },
          ],
        },
        {
          type: 'category',
          label: '💼 Nómina Electrónica',
          collapsible: true,
          collapsed: true,
          link: {
            type: 'generated-index',
            title: 'Documentación de Nómina Electrónica',
            description: 'Guías completas sobre campos de nómina, reemplazo y eliminación de documentos de nómina electrónica.',
            slug: '/ejemplos-nomina',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'payroll',
            },
          ],
        },
      ],
    },

    // ============================================
    // SECCIÓN 7: MARCO REGULATORIO DIAN
    // ============================================
    {
      type: 'category',
      label: '🏛️ Marco Regulatorio DIAN',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'regulatory-framework/overview',
          label: 'Descripción General',
        },
        {
          type: 'category',
          label: '📋 Factura Electrónica (FE)',
          collapsible: true,
          collapsed: false,
          items: [
            {
              type: 'doc',
              id: 'regulatory-framework/factura-electronica/intro',
              label: '📖 Introducción',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/factura-electronica/technical-annex',
              label: '📋 Especificaciones Técnicas',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/factura-electronica/tablas-equivalencias',
              label: '📊 Tablas de Equivalencias',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/factura-electronica/faq',
              label: '❓ Preguntas Frecuentes',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/factura-electronica/casos-especiales',
              label: '🎯 Casos Especiales',
            },
            {
              type: 'category',
              label: '⚙️ Anexo Técnico Detallado',
              collapsible: true,
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  id: 'regulatory-framework/factura-electronica/anexo-tecnico/validaciones',
                  label: '✅ Validaciones',
                },
                {
                  type: 'doc',
                  id: 'regulatory-framework/factura-electronica/anexo-tecnico/excepciones',
                  label: '⚠️ Excepciones',
                },
              ],
            },
            {
              type: 'doc',
              id: 'regulatory-framework/factura-electronica/ejemplos-aplicacion',
              label: '💡 Ejemplos Prácticos',
            },
          ],
        },
        {
          type: 'category',
          label: '💼 Nómina Electrónica',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'regulatory-framework/nomina-electronica/intro',
              label: '📖 Introducción',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/nomina-electronica/ejemplos',
              label: '💡 Ejemplos Prácticos',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/nomina-electronica/campos',
              label: '📋 Especificación de Campos',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/nomina-electronica/novedades',
              label: '📝 Tipos de Novedades',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/nomina-electronica/calculos',
              label: '📐 Fórmulas de Cálculo',
            },
          ],
        },
        {
          type: 'category',
          label: '📄 Documentos Equivalentes',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'regulatory-framework/documentos-equivalentes',
            },
          ],
        },
        {
          type: 'category',
          label: '📦 Documento Soporte',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'regulatory-framework/documento-soporte/intro',
              label: '📖 Introducción',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/documento-soporte/ejemplos',
              label: '💡 Ejemplos Prácticos',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/documento-soporte/validaciones',
              label: '✅ Validaciones Detalladas',
            },
          ],
        },
        {
          type: 'category',
          label: '🔄 RADIAN',
          collapsible: true,
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'regulatory-framework/radian/intro',
              label: '📖 Introducción',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/radian/flujos',
              label: '🔀 Flujos de Respuesta',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/radian/matriz',
              label: '📊 Matriz Sujeto-Evento-Rol',
            },
            {
              type: 'doc',
              id: 'regulatory-framework/radian/casos-uso',
              label: '💡 Casos de Uso',
            },
          ],
        },
        {
          type: 'doc',
          id: 'regulatory-framework/tablas-referencia',
          label: '🔗 Centro de Tablas de Referencia',
        },
        {
          type: 'doc',
          id: 'regulatory-framework/descargas-pdf',
          label: '📥 Descargas PDF - Anexos DIAN',
        },
      ],
    },
  ],
};

export default sidebars;
